version: '3.0'
services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
      - ./db-data:/data
    command: [ "redis-server", "/redis.conf" ]
    #container_name: some-docker-redis_redis_1